# Generated by Django 6.0.2 on 2026-02-13 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Student number must start with 25 followed by 6 digits', regex='^25\\d{6}$')])),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('hostler', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be in format: name25rollno@akgec.ac.in', regex='^[a-zA-Z]+25\\d+@akgec\\.ac\\.in$')])),
                ('phone_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 13 digits', regex='^\\d{10,13}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_signature', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
