# Generated by Django 6.0.2 on 2026-02-14 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email must end with @akgec.ac.in', regex='^[a-zA-Z]+25\\d+@akgec\\.ac\\.in$')])),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 12 digits', regex='^\\d{10,12}$')])),
                ('student_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student number must start with 25 and be 6 to 8 digits long', regex='^25\\d{4,6}$')])),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CS-IT', 'CS-IT'), ('CSE-DS', 'CSE-DS'), ('CS-HINDI', 'CS-HINDI'), ('CSE-AIML', 'CSE-AIML'), ('IT', 'IT'), ('AIML', 'AIML'), ('ECE', 'ECE'), ('ME', 'ME'), ('EN', 'EN'), ('CIVIL', 'CIVIL')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('hostler', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('is_present', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
