# Generated by Django 6.0.2 on 2026-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('hostler', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_signature', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
