# Generated by Django 6.0.2 on 2026-02-13 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField( max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 13 digits', regex='^\\d{10,13}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email must be in format: name25rollno@akgec.ac.in', regex='^[a-zA-Z]+25\\d+@akgec\\.ac\\.in$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Student number must start with 25 followed by 6 digits', regex='^25\\d{6}$')]),
        ),
    ]
